### PR TITLE
Find out who to blame when the template doesn't compile

### PR DESCRIPTION
**Pull request by pentix**
# Use continuous integration
#### Visualization 1

screenshot

#### Visualization 2

screenshot2

### CODE REVIEW

**Comment by mmathys** [comment]
but the template doesn't even compile bro

**Comment by mmathys** [comment]
link?

**Comment by pentix** [comment]
to?

**Comment by mmathys** [comment]
travis?

**Comment by pentix** [comment]
this? https://travis-ci.org/pentix/aw_template

**Comment by mmathys** [comment]
thanks?

**Comment by pentix** [comment]
you're welcome?

**Pull request merged**
